# Generated by Django 6.1.1 on 2026-09-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_theme_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='background_video',
            field=models.FileField(blank=True, help_text='Якщо завантажено — відео показується замість фото (mp4, без звуку, в циклі).', null=True, upload_to='site/video/', verbose_name='Фонове відео'),
        ),
    ]
