# Generated by Django 6.1.1 on 2026-09-26 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HighScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_score', models.PositiveIntegerField(default=0, verbose_name='Найкращий рахунок')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snake_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рекорд',
                'verbose_name_plural': 'Рекорди',
                'ordering': ['-best_score'],
            },
        ),
    ]
