# Generated by Django 6.1.1 on 2026-09-26 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relax', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='highscore',
            name='game',
            field=models.CharField(choices=[('snake', 'Змійка'), ('racing', 'Гонки')], default='snake', max_length=10),
        ),
        migrations.AlterField(
            model_name='highscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='highscore',
            unique_together={('user', 'game')},
        ),
    ]
